export const params = {
    container_selector: '[data-ca-block-manager-container-id]',
    row_selector: '[data-ca-block-manager-row-id]',
    grid_selector: '[data-ca-block-manager-grid-id]',
    block_selector: '[data-ca-block-manager-snapping-id]',
    blocks_place_selector: '[data-ca-block-manager-blocks-place]',
    block_disabled_class: 'bm-block-manager__block--disabled',
    block_got_up_class: 'bm-block-manager__block--got-up',
    block_got_down_class: 'bm-block-manager__block--got-down',
    block_menu_wrapper_bottom_class: 'bm-block-manager__menu-wrapper--bottom',
    block_menu_bottom_class: 'bm-block-manager__menu--bottom',
    menu_wrapper_selector: '[data-ca-block-manager-menu-wrapper]',
    menu_selector: '[data-ca-block-manager-menu]',
    action_selector: '[data-ca-block-manager-action]',
    switch_selector: '[data-ca-block-manager-switch]',
    switch_icon_selector: '[data-ca-block-manager-switch-icon]',
    switch_icon_show_selector: '[data-ca-block-manager-switch-icon="show"]',
    switch_icon_hide_selector: '[data-ca-block-manager-switch-icon="hide"]',
    switch_icon_hidden_class: 'bm-block-manager__icon--hidden',
    move_selector: '[data-ca-block-manager-move]',
    left_alignment_selector: '[data-ca-block-manager-is-left-alignment="true"]',
    right_alignment_selector: '[data-ca-block-manager-is-right-alignment="true"]',
    float_left_class: 'ty-float-left',
    float_right_class: 'ty-float-right',
    sortable_items_selector: '> *:not(#litecheckout_form):not(#litecheckout_final_section)',
    offset_threshold: 50,
    _hover_element: {},
    _self: {},
};
